export const leadLabels = {
	intID: 'Lead ID',
	leadName: 'Name',
	leadEmail: 'Email',
	leadPhoneNumber: 'Phone',
	leadWhatsappNumber: 'Whatsapp',
	nationality: 'Nationality',
	ip: 'IP',
	city: 'City',
	country: 'Country',
	countryCode: 'Country Code',
	attendanceDay: 'Attendance Day',
	leadAddress: 'Lead Address',
	// leadCampaign: 'Lead Campaign',
	leadCampaign: 'Campaign Name',
	// leadSourceDetails: 'Source Content',
	// leadSource: 'Source',
	leadSource: 'Platform',
	leadSourceDetails: 'Ad Name',
	// leadSourceMedium: 'Source Medium',
	leadSourceMedium: 'Placement',
	leadSourceChannel: 'Source Channel',
	pageUrl: 'Campaign URL',
	r_u_in_uae: 'In UAE',
	leadLang: 'Lead Language',
	lastNote: 'Last Note',
	budget: 'Budget',
	timetocall: 'Time To Call',
	managerAssigned: 'Manager',
	teamLeadAssigned: 'Team Lead',
	agentAssigned: 'Agent',
	leadStatus: 'Status',
	eLeadStatus: 'Main Status',
	isReleased: 'Released',
	endDate: 'End Date',
	startDate: 'Start Date',
	mainStatusSort: 'MStatus Sort',
	adset: 'Adset',
};

export const hiringLabels = {
	name: 'Name',
	email: 'Email',
	phone: 'Phone No',
	whatsApp: 'WhatsApp No',
	experienceYears: 'Experience in Years', // Uncomment if needed
};

export const dealsLabels = {
	manager: 'Manager',
	agent: 'Agent',
	spaDone: 'SPA Signed',
	dealStatus: 'Deal Status',
	closedBy: 'Closed By',
	commissionStatus: 'Commission Status',
	clientName: 'Client Name',
	clientNumber: 'Client Number',
	developer: 'Developer',
	salesPerson: 'Sales Person',
	projectName: 'Project Name',
	unitNumber: 'Unit Number',
	unitType: 'Unit Type',
	unitPrice: 'Unit Price',
	invoiceSent: 'Invoice Sent',
	downpaymentPaid: 'Downpayment Paid',
	bookingAmountPaid: 'Booking Amount Paid',
};

export const mainLeadStatusLabels = {
	interested: 'Interested',
	'not-interested': 'Not interested',
	'no-response': 'No response',
	'interested-seller': 'Interested Seller',
	'interested-buyer': 'Interested Buyer',
	hot: 'Hot',
	'secondary-request': 'Secondary request',
	show: 'Show',
	junk: 'Junk',
	deal: 'Deal',
	'change-agent': 'Change Agent',
};

export const leadStatusLabels = {
	active: 'Interested',
	sold: 'Sold',
	pending: 'Not Interested',
	reassigned: 'Reassigned',
	new: 'New',
	no_answer: 'No Answer',
	unreachable: 'Unreachable',
	callback: 'Callback',
	voice_mail: 'Voice Mail',
	wrong_number: 'Wrong Number',
	waiting: 'Waiting',
	follow_up: 'Follow Up',
	meeting: 'Meeting',
	follow_up_after_meeting: 'Follow Up After Meeting',
	deal: 'Deal',
	deal_out: 'Deal Out',
	whatsapp_send: 'Whatsapp Send',
	whatsapp_rec: 'Whatsapp Rec',
	will_attend_the_show: 'Will Attend the Show',
	attended_the_show: 'Attended the Show',
	junk: 'Junk',
	shift_project: 'Shift Project',
	broker: 'Broker',
	request: 'Request',
};
