import React from "react";
import { Box, Text } from "@chakra-ui/react";
import LeadGrid from "./LeadGrid";

const rejectedLeadsData = [
  {
    id: "2147",
    name: "Ali Khan",
    country: "Pakistan",
    nationality: "PAK",
    sourceContent: "5 Million",
    timeToCall: "2:00 PM",
    mStatus: "Cold",
    status: "Rejected",
    phone: "***********",
    whatsapp: "***********",
    leadTime: "Tue, Feb 18, 2025",
    note: "Not interested",
    buttonText: "Rejected",
    buttonBg: "#FF3B3B",
    buttonColor: "white",
    buttonHoverBg: "#E03333", // Darker red for hover
  },
  {
    id: "2148",
    name: "Emma Watson",
    country: "UK",
    nationality: "UK",
    sourceContent: "7 Million",
    timeToCall: "3:00 PM",
    mStatus: "Warm",
    status: "Rejected",
    phone: "***********",
    whatsapp: "***********",
    leadTime: "Wed, Feb 19, 2025",
    note: "Budget too low",
    buttonText: "Rejected",
    buttonBg: "#FF3B3B",
    buttonColor: "white",
    buttonHoverBg: "#E03333",
  },
  {
    id: "2148",
    name: "Emma Watson",
    country: "UK",
    nationality: "UK",
    sourceContent: "7 Million",
    timeToCall: "3:00 PM",
    mStatus: "Warm",
    status: "Rejected",
    phone: "***********",
    whatsapp: "***********",
    leadTime: "Wed, Feb 19, 2025",
    note: "Budget too low",
    buttonText: "Rejected",
    buttonBg: "#FF3B3B",
    buttonColor: "white",
    buttonHoverBg: "#E03333",
  },
  {
    id: "2148",
    name: "Emma Watson",
    country: "UK",
    nationality: "UK",
    sourceContent: "7 Million",
    timeToCall: "3:00 PM",
    mStatus: "Warm",
    status: "Rejected",
    phone: "***********",
    whatsapp: "***********",
    leadTime: "Wed, Feb 19, 2025",
    note: "Budget too low",
    buttonText: "Rejected",
    buttonBg: "#FF3B3B",
    buttonColor: "white",
    buttonHoverBg: "#E03333",
  },
  {
    id: "2148",
    name: "Emma Watson",
    country: "UK",
    nationality: "UK",
    sourceContent: "7 Million",
    timeToCall: "3:00 PM",
    mStatus: "Warm",
    status: "Rejected",
    phone: "***********",
    whatsapp: "***********",
    leadTime: "Wed, Feb 19, 2025",
    note: "Budget too low",
    buttonText: "Rejected",
    buttonBg: "#FF3B3B",
    buttonColor: "white",
    buttonHoverBg: "#E03333",
  },
];

const RejectedItems = () => {
  return <LeadGrid leads={rejectedLeadsData} />;
};

export default RejectedItems;